#==============================
# SPRING
#==============================
spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  cloud:
    config:
      uri: ${CONFIG_SERVICE_URL:http://localhost:8888}
      password: ${CONFIG_SERVICE_PASSWORD:password}
      username: user


#==============================
# APPLICATION
#==============================
app:
  jwt:
    secret: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e

